#!/usr/bin/perl -w

use strict;

my $PREFIX="/usr/local/bio/src/jnord";
my $JAVA = "/usr/java/jdk1.8.0_191-amd64/bin/java -Xmx128g ";

my $CLASSPATH = "$PREFIX/libs/commons-math3-3.6.1.jar:$PREFIX/libs/gral-core-0.11.jar:$PREFIX/libs/htsjdk-2.17.0-SNAPSHOT.jar:$PREFIX/bin/jnord_project-0.0.1-SNAPSHOT.jar";

if(@ARGV < 3){
	print STDERR "Usage: jnord --threads [threads] --genes [genes' list] --bamdir [bam dir] --sureselect [sureselect bed] --refgene [refGene.txt] --samples [Sample ID1] [Sample_ID2]...\n";
	exit;
}

MAIN:
{
	exec "$JAVA -cp $CLASSPATH jnord.Main2 " . join(" ", @ARGV);
}
